package _22_exception;

import java.util.Random;
import java.util.Scanner;

public class ExceptionTest5 {
	public static void main(String[] args) {
		
//		int n = (int)(Math.random() * 99) + 1;
		Random random = new Random();
		int n = random.nextInt(99) + 1;
		int you = 0;
		
		try (Scanner sc = new Scanner(System.in)){
			
			while(true) {
				System.out.print("1 ~ 99 사이 정수를 입력하세요 >> ");
				if (!sc.hasNext()) {
					System.out.println("값이 잘못 입력 되었습니다.");
					sc.nextLine();
					continue;
				}
				you = sc.nextInt();
				if (!(1 <= you && you <= 99 )) {
					System.out.println("값의 범위가 틀렸습니다. 1 ~ 99 사이 정수를 입력하세요");
				} else if (you != n){
					System.out.println("입력 값은" + you + "입니다");
				} else {
					System.out.println("맞았습니다. 컴퓨터가 생각하던 값은 " + n + "입니다");
					break;
				}
			}
		}
		System.out.println("종료");
	}
}
